{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6e7000db",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-01-08 17:04:11.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.558 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.563 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.565 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.571 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.662 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.947 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.947 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.948 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.949 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-08 17:04:11.950 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ===============================\n",
    "# Load trained artifacts\n",
    "# ===============================\n",
    "model = joblib.load(\"models/fatigue_model.pkl\")\n",
    "scaler = joblib.load(\"models/scaler.pkl\")\n",
    "feature_names = joblib.load(\"models/feature_names.pkl\")\n",
    "\n",
    "# ===============================\n",
    "# App UI\n",
    "# ===============================\n",
    "st.set_page_config(page_title=\"FatigueInsight\", layout=\"centered\")\n",
    "\n",
    "st.title(\"FatigueInsight: Cognitive Fatigue Predictor\")\n",
    "st.write(\"Predicts user fatigue level based on interaction patterns.\")\n",
    "\n",
    "st.sidebar.header(\"Input Session Data\")\n",
    "\n",
    "session_duration = st.sidebar.number_input(\n",
    "    \"Session Duration (minutes)\", min_value=1, value=30\n",
    ")\n",
    "decision_count = st.sidebar.number_input(\n",
    "    \"Decision Count\", min_value=0, value=10\n",
    ")\n",
    "undo_count = st.sidebar.number_input(\n",
    "    \"Undo Count\", min_value=0, value=2\n",
    ")\n",
    "error_rate = st.sidebar.number_input(\n",
    "    \"Error Rate (0–1)\", min_value=0.0, max_value=1.0, value=0.1, step=0.01\n",
    ")\n",
    "break_taken = st.sidebar.selectbox(\n",
    "    \"Break Taken?\", [\"No\", \"Yes\"]\n",
    ")\n",
    "time_of_day = st.sidebar.selectbox(\n",
    "    \"Time of Day\", [\"Morning\", \"Afternoon\", \"Evening\"]\n",
    ")\n",
    "\n",
    "# ===============================\n",
    "# Prepare input dataframe\n",
    "# ===============================\n",
    "input_df = pd.DataFrame({\n",
    "    \"session_duration\": [session_duration],\n",
    "    \"decision_count\": [decision_count],\n",
    "    \"undo_count\": [undo_count],\n",
    "    \"error_rate\": [error_rate],\n",
    "    \"break_taken\": [1 if break_taken == \"Yes\" else 0],\n",
    "    \"time_of_day_Morning\": [1 if time_of_day == \"Morning\" else 0],\n",
    "    \"time_of_day_Afternoon\": [1 if time_of_day == \"Afternoon\" else 0],\n",
    "    \"time_of_day_Evening\": [1 if time_of_day == \"Evening\" else 0],\n",
    "})\n",
    "\n",
    "# Align columns with training\n",
    "input_df = input_df.reindex(columns=feature_names, fill_value=0)\n",
    "\n",
    "# ===============================\n",
    "# Prediction\n",
    "# ===============================\n",
    "scaled_input = scaler.transform(input_df)\n",
    "prediction = model.predict(scaled_input)[0]\n",
    "\n",
    "st.subheader(\"Predicted Fatigue Level\")\n",
    "\n",
    "if prediction == 1:\n",
    "    st.error(\"High Cognitive Fatigue Detected\")\n",
    "else:\n",
    "    st.success(\"Low Cognitive Fatigue Detected\")\n",
    "\n",
    "# ===============================\n",
    "# Feature Contribution (Model Coefficients)\n",
    "# ===============================\n",
    "st.subheader(\"Feature Importance (Model-Based)\")\n",
    "\n",
    "importance = pd.Series(\n",
    "    model.coef_[0],\n",
    "    index=feature_names\n",
    ").sort_values()\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "importance.plot(kind=\"barh\")\n",
    "plt.xlabel(\"Impact on Fatigue Prediction\")\n",
    "plt.tight_layout()\n",
    "st.pyplot(plt)\n",
    "\n",
    "# ===============================\n",
    "# Note about SHAP\n",
    "# ===============================\n",
    "st.info(\n",
    "    \"SHAP explainability is disabled due to Python 3.13 compatibility. \"\n",
    "    \"The deployed version uses stable model coefficients for interpretation.\"\n",
    ")\n"
   ]
  },
  {
   "id": "3fa792c0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
